config/routes.rb
Rails.application.routes.draw do
  resources :post_comments
  get 'pages/about'
  get 'pages/contact'
  get 'pages/resources'
  devise_for :admin_users, ActiveAdmin::Devise.config

  get 'catagories/index'
  get 'catagories/edit'
  get 'catagories/new'
  get 'catagories/show'
  get 'categories/index'
  get 'categories/new'
  get 'categories/edit'
  get 'categories/show'
  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  resources :posts
  resources :categories
  match '/about' , :to =>'pages#about',:via => [:get, :post]
  match '/contact' , :to =>'pages#contact',:via => [:get, :post]
  match '/resources' , :to =>'pages#resources',:via => [:get, :post]
  ActiveAdmin.routes(self)
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :category
  belongs_to :admin_user
  has_many :post_comments , :dependent => :destroy
  validates :title , :presence => true
  validates_length_of :body , :minimum => 10
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :post

  validates_presence_of :name
  validates_length_of :name , :within => 2..20
  validates_presence_of :body

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :all_categories
  helper_method :all_posts

  def all_categories
    @categories = Category.all
  end

  def all_posts
    @posts = Post.all
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
   @title = @category.name
    @post = @category.posts
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end

  def resources
  end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < InheritedResources::Base

  def create
    @post_comment = PostComment.new(post_params)
    if @post_comment.save
      flash[:notice] = "Comment created Successfully"
      redirect_to(@post_comment.post)
    else
      flash[:notice] = "Error in creating post comment : #{@post_comment.errors}"
      redirect_to(@post_comment.post)
    end
  end







    def post_params
      params.require(:post_comment).permit(:name, :email, :body, :post_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
    @user =AdminUser.all
    @post_comment =PostComment.new(:post => @post)
  end

  def new
    @post = Post.new
  #  @category =Category.all
  end

  def create
    @post = Post.new (user_params)
    if @post.save
      redirect_to posts_path , :notice => "New Post created Successfully"
    else
      render "new"
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(user_params)
      redirect_to post_path ,:notice => "Post Updated Successfully"
    else
      render "edit"
    end
  end

  def destroy
    @post =Post.find(params[:id])
    @post.destroy
    redirect_to posts_path , :notice => "Post deleted Successfully"
  end

private

def user_params
  params.require(:post).permit(:title,:body,:category_id)
end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/catagories_helper.rb
module CatagoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/index.html.erb
<div class="post">
<h1>Listing Categories</h1>
<ul>
<% @categories.each do |c| %>
 <li><%=link_to c.name,c%></li>
 <%end %>
 </ul>
 </div>

app/views/categories/show.html.erb
<% if @post.each do |post| %>
  <div class="post">
  <h2 class="title"><%=link_to post.title, post %></h2>
  <div class="entry"><%=post.body %></div>
  <div class="byline">
    <p class="meta">May 07, 2012 Posted by <a href="#">Someone</a></p>
    <p class="links"><a href="post.html">Read More</a>&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;<a href="#" title="b0x w">Comments</a></p>
  </div>
</div>
<% end.empty? %>
<p style="color:white">Sorry no post for this Category</p>
    <% end %>

app/views/home/index.html.erb
  <% @posts.each do |post| %>
    <div class="post">
      <h2 class="title"><%=link_to post.title, post %></h2>
      <div class="entry"><%=post.body %></div>
      <div class="byline">
        <p class="meta">May 07, 2012 Posted by <%=post.admin_user.name%></p>
        <p class="links"><%=link_to "Read More..", post %></p>
      </div>
      </div>
  <% end %>

app/views/layouts/application.html.erb
<%= render "partials/header" %>
    	<div id="page">
    		<div id="page-bgtop">
    			<div id="page-bgbtm">
    				<div id="content">
              <div class="flash-message">
              <% flash.each do |key,value| %>
              <p><%=value%></p>
              <% end %>
            </div>
              <%= yield %><!--this is the main view-->
    					<div style="clear: both;">&nbsp;</div>
    				</div>
    				<!-- end #content -->
    				<%= render "partials/sidebar" %>
    				<div style="clear: both;">&nbsp;</div>
    			</div>
    		</div>
    	</div>
    	<!-- end #page -->
    	<div id="footer">
    		<p>&copy; 2013, My Ruby Blog - Sample Project</p>
    	</div>
    </div>
    <!-- end #footer -->
  </body>
</html>

app/views/pages/about.html.erb
<div class="post">
<h1>About my Ruby Blog</h1>
<p>This one is a biggie, which is why I’m sharing it first. #seewhatididthere? Your About Page should be ALL about the value you give to your readers. Yes, people want to learn about you (we’ll get into that, too), but they also want to know how YOU are going to help THEM. So, before you start writing your About Page, get clear on what it is that makes your blog useful to your readers and who your blog is intended for. (Psst I’ve got a free worksheet at the bottom of this post, to help you answer this question).</p>
</div>

app/views/pages/contact.html.erb
<div class="post">
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>
</div>

app/views/pages/resources.html.erb
<div class="post">
<h1>Pages#resources</h1>
<p>Find me in app/views/pages/resources.html.erb</p>
</div>

app/views/partials/_header.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myrubyblog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<link href="http://fonts.googleapis.com/css?family=Abel" rel="stylesheet" type="text/css" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div id="wrapper">
    	<div id="header-wrapper">
    		<div id="header">
    			<div id="logo">
    				<h1><a href="#">My Ruby Blog</a></h1>
    				<p>Learning Ruby on Rails</p>
    			</div>
    			<div id="menu">
    				<ul class="main-nav">
    					<li><%=link_to "Home",root_path%></li>
    					<li><%=link_to "About",about_path%></li>
              <li><%=link_to "Blog",posts_path%></li>
              <li><%=link_to "Contact",contact_path %></li>
              <li><%=link_to "Resources",resources_path %></li>
    				</ul>
    			</div>
    		</div>
    	</div>
    	<!-- end #header -->

app/views/partials/_post_comment.html.erb
<div class="post_comment">
  <i><%=h post_comment.name %> says: </i><br />
  <%= simple_format h(post_comment.body) %>
</div>

app/views/partials/_sidebar.html.erb
<div id="sidebar">
  <ul>
    <li>
      <div id="search" >
        
      </div>
      <div style="clear: both;">&nbsp;</div>
    </li>
    <li>
      <h2>Get The Framework</h2>
      <p>You can download Ruby and/or Ruby on Rails for free right now
                                                    <br />
                                                    <a style="color:#D93544;" href="http://rubyonrails.org/download" target="blank">GET IT NOW</a>
                                                </p>
    </li>
    <li>
      <h2>Categories</h2>
      <ul>
        <% all_categories.each do |cat| %>
          <li><%=link_to cat.name,category_path(:id => cat.id)%></li>
        <% end %>

      </ul>
    </li>
    <li>
      <h2>Blogroll</h2>
      <ul>
        <% all_posts.each do |post| %>
          <li><%=link_to post.title,post_path(:id => post.id)%></li>
        <% end %>
      </ul>
    </li>

  </ul>
</div>
<!-- end #sidebar -->

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <div class="post">
  <h2 class="title"><%=link_to post.title, post %></h2>
  <div class="entry"><%=post.body %></div>
  <div class="byline">
    <p class="meta">May 07, 2012 Posted by <%=post.admin_user.name%></p>
    <p class="links"><%=link_to "Read More..", post %></p>
  </div>
</div>
<% end %>

app/views/posts/show.html.erb
<div class="post">
  <h1><%=@post.title%></h1>
  <small><%=@post.created_at.strftime("%b %d %Y")%></small>
  <p>Created by: <%=@post.admin_user.name%></p>
  <p><%=@post.body%></p>
  <p>Category:<%=link_to @post.category.name,category_path(:id => @post.category.id)%></p>
  <p><%=link_to "Back",posts_path%></p>
  <h3>Add Comment below</h3>
  <hr />
  <%= form_for @post_comment do |f| %>
    <%= f.hidden_field :post_id %>
    <p>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </p>
    <p>
      <%=f.label :email %><br>
      <%=f.text_field :email %>
    </p>
    <p>
      <%=f.label :body %><br>
      <%=f.text_area :body %>
    </p>
    <p>
      <%=f.submit "Post Comment" %>
    </p>
  <%end%>
  <hr />
  <%= render :partial  => 'partials/post_comment' ,:collection => @post.post_comments%>
</div>